### ISSUE TITLE
no information on the lock screen

### ISSUE THREAD

**Issue by siggi1984** [toasterofbread/spmp#103]
no information is displayed on the lock screen. title or artist displayed. it just shows unknown. the same in the car if you listen via Bluetooth on the car radio is also simply displayed as unknown.

see the screenshot.

![Screenshot_20230728-193000](https://github.com/toasterofbread/spmp/assets/103368536/182f0e07-ff4e-4f05-b889-5828aa87086c)

**Comment by toasterofbread** [comment]
What version of Android are you using? Please fill in the bug report template in future.

**Comment by siggi1984** [comment]
> 

Android 9, Samsung Galaxy a8

**Comment by PFARN** [comment]
> What version of Android are you using? Please fill in the bug report template in future.

![Screenshot_20230728-152004](https://github.com/toasterofbread/spmp/assets/68994473/cad7a40e-1298-423f-925f-769799dde6fa)

Something similar here.

Android 13. AOSPA. Redmi Note 10. I think this is the same bug as the AoD one.

**Comment by toasterofbread** [comment]
Thanks for the info, will look into this

**Comment by toasterofbread** [comment]
I was able to fix the issue that @PFARN mentioned, but I wasn't able to reproduce the original issue (it's probably device-specific).
They're similar issues though, so it's possible that both were fixed in one go. If @siggi1984 could [test](https://github.com/toasterofbread/spmp/actions/runs/5861231960) the fix that would be great.
