### ISSUE TITLE
Custom image Discord Rich Presence

### ISSUE THREAD

**Issue by Urbexed** [toasterofbread/spmp#152]
How to edit this ?

**Comment by toasterofbread** [comment]
What do you want to edit exactly? Discord status images aren't intended to be editable, it simply displays the current song image and the artist image, although it should be possible to implement this.

Also, are you trying to paste an image in SpMp or into Github?

**Comment by Urbexed** [comment]
> Que veux-tu modifier exactement ? Les images d'état de Discord ne sont pas destinées à être modifiables, elles affichent simplement l'image de la chanson actuelle et l'image de l'artiste, bien qu'il devrait être possible de l'implémenter.
> 
> Essayez-vous également de coller une image dans SpMp ou dans Github ?

No image is displayed on discord for my case

And what does the line below this text mean: 
![Screenshot_2023-09-30-10-04-24-382_com toasterofbread spmp-edit](https://github.com/toasterofbread/spmp/assets/116701347/6191ddeb-d737-4509-a561-7c02c7a244e2)

**Comment by toasterofbread** [comment]
This might have been fixed by 34538c687294554f0de371f41e9514e63ad6835e, please try [the latest build](https://github.com/toasterofbread/spmp/actions/runs/6412011135) and see if it works.

<br/>

> And what does the line below this text mean

![image](https://github.com/toasterofbread/spmp/assets/44363049/0aa22bd7-d3e3-4af0-97a7-3be6e6561b0c)

It's the bottommost text, in this case "YOASOBI - アイドル"
