### ISSUE TITLE
[Bug] Duplicate file video_id leads to app crash

### ISSUE THREAD

**Issue by mxvin** [toasterofbread/spmp#153]
Downloaded song playlist, allowed you to re-download the downloaded song, leads to duplicate file saved with `video_id (1).webm`

**Steps To Reproduce**
1. Make file on the song directory have 2 identical video_id but named `video_id` and `video_id xxxx.webm`
2. open downloaded song list (+ it's not that intuitive to press music button to switch between online↔offline library ~ another topic :smile_cat: )
3. App hangs and crash

**Environment**
- OS:  Android 12
- SpMp version: 0.2.1  
- Accounts : non-applicable

Still new on your project. Finally, found solution that _**almost**_ fit what I want

**Comment by toasterofbread** [comment]
Should be working now. 

Seems this was an issue specific to when you have a custom library location set (which is why I never found it). With the default location it would normally just overwrite the file but with the custom location the OS creates a new file for some reason. I've just made it entirely skip downloading songs that have already been downloaded now.

**Comment by toasterofbread** [comment]
> it's not that intuitive to press music button to switch between online↔offline library ~ another topic 😸

The music button doesn't switch between online and offline libraries, it switches between your recommendation feed and your library (which contains both online and offline content).
