### ISSUE TITLE
[Bug] Top lyrics wrap when they shouldn't

### ISSUE THREAD

**Issue by LiphiTC** [toasterofbread/spmp#156]
Sometimes lyrics are moved to a new line where it can fit on one.

- Lyrics Source: KuGou
- Lyrics Id: 0dc45741ee7041eee796ac8afb73681d

- Spmp version: 0.2.1 from F-droid

![Screenshot_20231004-004058_SpMp_1](https://github.com/toasterofbread/spmp/assets/48130941/5392bdfd-d01f-4a90-9050-198bf29678ae)

**Comment by toasterofbread** [comment]
Sorry about this, I actually fixed this before making v0.2.1 but for some reason the fix was reverted and I only reapplied the fix in 63e9b20b75afc5325d31957a02218486d695f164 shortly after the release. 

This should be fixed in v0.2.2 which I'll be releasing by the end of the week. You can try a [pre-release build](https://github.com/toasterofbread/spmp/actions) in the meantime, which should include the fix if it was built since 63e9b20b75afc5325d31957a02218486d695f164.

**Comment by LiphiTC** [comment]
Oh, okay then. Thanks for quick response
