### ISSUE TITLE
[Feature] Option to name download files by song title

### ISSUE THREAD

**Issue by Berserk0001** [toasterofbread/spmp#173]
After the songs are downloaded the names are not according to the song names...
![Screenshot_20231017-112327_ZArchiver](https://github.com/toasterofbread/spmp/assets/125671174/71120096-56d8-48fb-9fff-e8c16a858cc0)

**Comment by Berserk0001** [comment]
Also please attach the image of the songs to the downloaded file...

**Comment by toasterofbread** [comment]
Song files are named with their unique YouTube video ID. I could technically implement your suggestion as an option, but it could lead to all sorts of issues like duplicate titles and I would have to handle characters that can't be used in Unix filenames somehow.

What would your use case for this be?

**Comment by Berserk0001** [comment]
Suppose i want to transfer the downloaded songs to other device...And you can guess that what it would be like if you can't see the name of the songs but some weird ID characters..Right?

**Comment by toasterofbread** [comment]
I won't add an option to change how files are stored within the app's own library, it's too much complexity for such an important system and offers no benefit to the usability of the app itself.

However, I could definitely add a button that would trigger a transfer of all the library content to another folder with the option to name the files using item titles rather than IDs (see #174).

**Comment by toasterofbread** [comment]
Guess I kind of forgot that file metadata existed. Downloaded files are now named by the song's title, and the ID is stored as metadata within the file (along with a few other things like the artist name). 

Couldn't figure out how to get webm metadata working so I had to change the default format to m4a, but this hopefully shouldn't affect anything.

**Comment by Berserk0001** [comment]
M4a is the best..No problem should happen..
