### ISSUE TITLE
Cannot open general settings

### ISSUE THREAD

**Issue by DestinyofYeet** [toasterofbread/spmp#206]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/toasterofbread/spmp/actions/workflows/android.yml).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce

1. Open the spmp debug ap
2. Click on the settings icon in the top left
3. Try to open up the "General" category

### Expected behavior

The category should open

### Actual behavior

The app crashes.

### Logs

[spmp_debug_log.txt](https://github.com/toasterofbread/spmp/files/13420268/spmp_debug_log.txt)

### SpMp version

0.2.4 edf3bd3

### Android version

Android 12 - Lineage OS

**Comment by toasterofbread** [comment]
Are you sure this occurs on 0.2.4? That's very strange...

**Comment by DestinyofYeet** [comment]
I just grabbed the latest debug version and it occurs on there, so I guess yes?

**Comment by toasterofbread** [comment]
The latest debug version isn't 0.2.4, because it was created after it and contains code that 0.2.4 doesn't contain. The only thing that's 0.2.4 is the specific commit that was [released](https://github.com/toasterofbread/spmp/releases/tag/v0.2.4) as 0.2.4, everything else is just another non-release commit.

I would strongly advise against using debug builds as they come out unless you're testing something specific, as things are kind of expected to break as I don't test everything thoroughly and some commits are halfway through a feature or fix. If something breaks in a fairly significant way like this in a debug build, then I probably already know about it anyway.

I still appreciate the report though, I'll keep this open until it's fixed on main.
