### ISSUE TITLE
only 100 songs show up in liked songs playlist 

### ISSUE THREAD

**Issue by PeterHindes** [toasterofbread/spmp#261]
### Checklist

- [X] I am able to reproduce the bug with the latest debug version ([Android](https://nightly.link/toasterofbread/spmp/workflows/build-android/main), [Linux](https://nightly.link/toasterofbread/spmp/workflows/build-linux/main), [Windows](https://nightly.link/toasterofbread/spmp/workflows/build-windows/main))
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce

Have more than 100 songs in liked songs playlist.
Open it with spmp
Only 100 songs show up.

### Expected behavior

All songs should show up

### Actual behavior

Only 100 songs show

### Logs

Not needed

### SpMp version

0.3.0

### SpMp platform

Android

### OS version

Android 14 pixel march update

**Comment by Xenorio** [comment]
This seems to not only occur for liked songs, but for any playlist

I've got a playlist containing 1189 songs: https://www.youtube.com/playlist?list=PLSaT9-D0jN2ToFQR-K1SESclUj9Z6szC8

In the SpMp playlist view, it says there are 1127 songs (probably because not counting those which were made unavailable). However, it can only load 93 of them. Clicking the "load more" arrow at the bottom does nothing after that.

This also means that I am unable to download the playlist for offline playback. The "select all" button only selects loaded songs, and there is no "download entire playlist" button.

This behavior does not seem to have effect on actual playback. I am able to go beyond those 93 songs using the skip button. 

SpMp 0.3.1
/e/os 1.21 (Android 13)
Fairphone 5
