### ISSUE TITLE
Font style

### ISSUE THREAD

**Issue by Ubee2268** [toasterofbread/spmp#69]
Most of the things are working fine so far, thank you for that! If you can please add an option to change the application font, that would be great!

**Comment by toasterofbread** [comment]
I'd love to add an option for the font at some point, but I've had issues with lyrics displaying incorrectly with some fonts (which is why the default English font isn't the nicest).
At some point I'll figure out what's wrong and find a better default font, and add an option for changing the it. Thanks for the suggestion!

**Comment by toasterofbread** [comment]
I've fixed the issue with the lyrics I mentioned added an option to set the app font to default, system, or a specific font. The current font (HC Maru Gothic) will only be applied by default when the UI language is Japanese, so otherwise the default font is the system font.

I haven't added any extra fonts (yet) but I'm open to suggestions.
